### PR TITLE
Refactor app.ts, users.controller.ts, and zodSchema.ts, fix bugs, and add new features

### PR DESCRIPTION
**Pull request by BlackBoxBanner**
This pull request includes multiple changes to improve the codebase. It refactors app.ts, users.controller.ts, and zodSchema.ts files, fixes bugs in changePasswordController and uploadController, comments out unused models and relations in schema.prisma, and adds a new searchUserGetController to users.controller.ts and users.route.ts.

### CODE REVIEW

**Review by redbiiddsun — COMMENTED** [review]
let me see this again tmr

**Review by redbiiddsun — APPROVED** [review]
LGTM

**Comment by redbiiddsun** [comment]
@BlackBoxBanner u can merge

**Comment by BlackBoxBanner** [comment]
review again since there is some conflict with your last pr

**Review by redbiiddsun — APPROVED** [review]
LGTM

**Pull request merged**
