### PR TITLE
10 build authentication api

### PR DESCRIPTION
**Pull request by BlackBoxBanner**
- [x] signin
- [x] signout
- [x] register

### CODE REVIEW

**Review by redbiiddsun — COMMENTED** [review]
Quite good, but the better way is to create a new branch

**Comment by BlackBoxBanner** [comment]
Can you name what branch I need to separate into. In this branch I did create authentication and image uploading. If you are available to review and fix conflicts then I will separate branches for you. The reason I did this is because if parents branch are not complete and merge to development branch then I cannot continue work on it since the need of using extra function. @redbiiddsun

**Comment by BlackBoxBanner** [comment]
@BlackBoxBanner @redbiiddsun This is the updated branch.

**Review by redbiiddsun — APPROVED** [review]
LGTM

**Pull request merged**
